CREATE TABLE USR (
	ID INT PRIMARY KEY auto_increment,
	NAME VARCHAR (25) NOT NULL,
	PASSWORD VARCHAR (50) NOT NULL,
	USER_TYPE TINYINT,
	STATE TINYINT,
	EMAIL VARCHAR (250) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME DATETIME
);

CREATE TABLE AREA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR (25) NOT NULL,
	USER_ID INT NOT NULL,
	DESCIPTION VARCHAR (300),
	CREATE_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME DATETIME
);

CREATE TABLE TARGET (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR (150) NOT NULL,
	DESCRIPTION VARCHAR (300),
	USER_ID INT NOT NULL,
	AREA_ID INT NOT NULL,
	PREDICT_COMPLETE_DATE DATE NOT NULL,
	COMPLETE_DATE DATE NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME DATETIME,
	STATE TINYINT
);

CREATE TABLE TASK (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR (150) NOT NULL,
	DESCRIPTION VARCHAR (300),
	USER_ID INT NOT NULL,
	TARGET_ID INT NOT NULL,
	PLAN_COMPLETE_DATE DATE NOT NULL,
	COMPLETE_DATE DATE NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME DATETIME,
	IS_PRIVACY TINYINT,
	STATE TINYINT NOT NULL,
	DIFFICULT_LEVEL INT,
	PRIORITY INT
);

CREATE TABLE TASK_TRACE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TASK_ID INT NOT NULL,
	SUMMARY LONGTEXT,
	CREATE_TIME TIMESTAMP NOT NULL
);

INSERT INTO USR (
	NAME,
	PASSWORD,
	user_type,
	state,
	email,
	create_time,
	update_time
)
VALUES
	(
		'peichangqiang',
		'pcq1993116',
		0,
		0,
		'1156368718@qq.com',
		now(),
		now()
	);

